version: '3.8'

services:
    postgres:
        image: postgres:13
        shm_size: '2gb'
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: postgres
            POSTGRES_DB: development
        ports:
            - '9002:5432'
        volumes:
            - ./dev_db_init.sql:/docker-entrypoint-initdb.d/dev_db_init.sql
